CREATE TABLE CATEGORY(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);
CREATE MATERIALIZED VIEW duck AS SELECT * FROM CATEGORY;
SELECT * from duck;
INSERT INTO CATEGORY (name) VALUES ('Опции для серверов');
SELECT * from CATEGORY;
SELECT * FROM duck;
REFRESH MATERIALIZED VIEW duck;
SELECT * FROM duck;
